name: A corazon de tango
favicon: null
layout_spectrum: 1
typography_spectrum: 0.77828
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8522806155961007
  lightness: 0.7321591307409108
  saturation: 0.8487875883001834
  rhythmicContrast: 0.802189766895026
purpose: []
